apiVersion: k3d.io/v1alpha4
kind: Simple
image: docker.io/rancher/k3s:v1.24.4-k3s1
servers: 1
agents: 3
ports:
  - port: 0.0.0.0:80:80
    nodeFilters:
      - agent:0:direct
  - port: 0.0.0.0:443:443
    nodeFilters:
      - agent:0:direct
  - port: 0.0.0.0:5053:53/udp
    nodeFilters:
      - agent:0:direct
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --kube-proxy-arg=conntrack-max-per-core=0
        nodeFilters:
          - server:*
      - arg: --kube-proxy-arg=conntrack-max-per-core=0
        nodeFilters:
          - agent:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true