---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system