---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: linkerd-viz
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/linkerd-viz
  prune: true
  dependsOn:
    - name: linkerd
  sourceRef:
    kind: GitRepository
    name: flux-system