---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: open-telemetry
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/open-telemetry
  prune: true
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system