---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 1h0m0s
  timeout: 10m0s
  targetNamespace: monitoring
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 39.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      enabled: false
    prometheus:
      prometheusSpec:
        enableFeatures:
          - remote-write-receiver
        additionalScrapeConfigs:
          - name: additional-scrape-configs
            key: additional-scraping.yaml
            