---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: finalizers
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/finalizers
  prune: true
  dependsOn:
    - name: prometheus
    - name: linkerd
    - name: linkerd-viz
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
