---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: finalizers
spec:
  interval: 1h0m0s
  path: ./k8s/infrastructure/source/finalizers
  prune: true
  dependsOn:
   - name: kube-prometheus-stack
   - name: monitoring-config
  sourceRef:
    kind: GitRepository
    name: flux-system