apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - linkerd.yaml
  - linkerd-viz.yaml
  - kube-prometheus-stack.yaml
  - monitoring-config.yaml
  - finalizers.yaml

namespace: flux-system
