apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cert-manager.yaml
  - monitoring-ns.yaml
  - prometheus-community-repo.yaml
  - prometheus.yaml
  - linkerd.yaml
  - finalizers.yaml

namespace: flux-system