---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infrastructure/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
      kind: Kustomization
      name: finalizers
      namespace: flux-system
