apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ingress.yaml
- sync.yaml
- github.com/stefanprodan/podinfo//kustomize

namespace: podinfo
labels:
- includeSelectors: true
  pairs:
    app: podinfo
    tier: application
patches:
- path: patches/security-context.yaml
