---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      containers:
      - name: podinfod
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          # runAsNonRoot: true
  # securityContext:
  #   runAsNonRoot: true