apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: additional-scrape-configs
    files:
      - additional-scraping.yaml

generatorOptions:
  disableNameSuffixHash: true

resources:
  - monitoring-ns.yaml
  - kube-prometheus-stack.yaml
